<style>
    /* body {font-family: Arial, Helvetica, sans-serif;}
    * {box-sizing: border-box;} */

    input[type=text], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    margin-top: 6px;
    margin-bottom: 16px;
    resize: vertical;
    }

    input[type=submit] {
    background-color: #4CAF50;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    }

    input[type=submit]:hover {
    background-color: #45a049;
    }

    .container-formaa {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
    }
 
</style>

<div class="container-formaa">
  <form action="<?php echo  $this->getUrl("contactus/")?>" method="post" autocomplete="off">
    <label for="fname">Your Name</label>
    <input type="text" id="name" name="name" placeholder="Your name..">

    <label for="lname">Email</label>
    <input type="email" id="email" name="email" placeholder="Your Email..">

    <label for="lname">Subject</label>
    <input type="text" id="subject" name="subject" placeholder="Subject">
 

    <label for="subject">Message</label>
    <textarea id="subject" name="message" placeholder="Write Message.." style="height:200px"></textarea>

    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */  echo $block->getFormKey(); ?>" />

    <input type="submit" name="submitClick" value="Send Email">
  </form>
</div>